export const PLACES = [
  {
    id: '1',
    place_id: 'ChIJIQBpAG2ahYAR_6128GcTUEo',
    title: 'San Francisco',
    subtitle: 'CA, USA',
    description: 'San Francisco, CA, USA',
    structured_formatting: {
      main_text: 'San Francisco',
      main_text_matched_substrings: [{length: 8, offset: 0}],
      secondary_text: 'CA, USA',
    },
    terms: [
      {offset: 0, value: 'San Francisco'},
      {offset: 15, value: 'CA'},
      {offset: 19, value: 'USA'},
    ],
    types: ['locality', 'political', 'geocode'],
  },
  {
    id: '2',
    place_id: 'ChIJXSModoWLGGARILWiCfeu2M0',
    title: 'Tokyo',
    subtitle: 'Japan',
    description: 'Tokyo, Japan',
    structured_formatting: {
      main_text: 'Tokyo',
      main_text_matched_substrings: [{length: 4, offset: 0}],
      secondary_text: 'Japan',
    },
    terms: [
      {offset: 0, value: 'Tokyo'},
      {offset: 7, value: 'Japan'},
    ],
    types: ['colloquial_area', 'locality', 'political', 'geocode'],
  },
  {
    id: '3',
    place_id: 'ChIJW6AIkVXemwARTtIvZ2xC3FA',
    title: 'Rio de Janeiro',
    subtitle: 'State of Rio de Janeiro, Brazil',
    description: 'Rio de Janeiro, State of Rio de Janeiro, Brazil',
    structured_formatting: {
      main_text: 'Rio de Janeiro',
      main_text_matched_substrings: [{length: 3, offset: 0}],
      secondary_text: 'State of Rio de Janeiro, Brazil',
    },
    terms: [
      {offset: 0, value: 'Rio de Janeiro'},
      {offset: 16, value: 'State of Rio de Janeiro'},
      {offset: 41, value: 'Brazil'},
    ],
    types: ['locality', 'political', 'geocode'],
  },
  {
    id: '4',
    place_id: 'ChIJW6AIkVXemwARTtIvZ2xC3FA',
    title: 'Manila',
    subtitle: 'State of Rio de Janeiro, Brazil',
    description: 'Rio de Janeiro, State of Rio de Janeiro, Brazil',
    structured_formatting: {
      main_text: 'Rio de Janeiro',
      main_text_matched_substrings: [{length: 3, offset: 0}],
      secondary_text: 'State of Rio de Janeiro, Brazil',
    },
    terms: [
      {offset: 0, value: 'Rio de Janeiro'},
      {offset: 16, value: 'State of Rio de Janeiro'},
      {offset: 41, value: 'Brazil'},
    ],
    types: ['locality', 'political', 'geocode'],
  },
  {
    id: '5',
    place_id: 'ChIJW6AIkVXemwARTtIvZ2xC3FA',
    title: 'Lisbon',
    subtitle: 'State of Rio de Janeiro, Brazil',
    description: 'Rio de Janeiro, State of Rio de Janeiro, Brazil',
    structured_formatting: {
      main_text: 'Rio de Janeiro',
      main_text_matched_substrings: [{length: 3, offset: 0}],
      secondary_text: 'State of Rio de Janeiro, Brazil',
    },
    terms: [
      {offset: 0, value: 'Rio de Janeiro'},
      {offset: 16, value: 'State of Rio de Janeiro'},
      {offset: 41, value: 'Brazil'},
    ],
    types: ['locality', 'political', 'geocode'],
  },
];
